version: "1.0"

volumes: 
  newsletter-microservice: null
  users-microservice: null
  deno-microsvice: null
  ui-starter-app: null
  xsj-consulting-app: null

services:
  newsletter-microservice:
    build: 
      context: ../xsj-newsletter-microservice/
      dockerfile: Dockerfile.dev
    image: newsletter-microservice:latest
    container_name: xsj-newsletter-microservice
    environment:
      PORT: 420
      HOST: 0.0.0.0
    ports:
      - 420:420

  users-microservice:
    build:
      context: ../xsj-users-microservice/
      dockerfile: Dockerfile.dev
    image: users-microservice:latest
    container_name: xsj-users-microservice
    environment:
      PORT: 1017
      HOST: 0.0.0.0
    ports:
      - 1017:1017

  deno-microservice:
    build:
      context: ../xsj-deno-microservice/
      dockerfile: Dockerfile.dev
    image: deno-microservice:latest
    container_name: xsj-deno-microservice
    environment:
      PORT: 4200
      HSOT: 0.0.0.0
    ports:
     - 4200:4200

  ui-starter-app:
    build:
      context: ../.xsj-ui-starter-app.nosync/
      dockerfile: Dockerfile.dev
    image: ui-starter-app:latest
    container_name: xsj-ui-starter-app
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - 3000:3000
      
   xsj-consulting-app:
    build:
      context: ../xsj-consulting-ui/
      dockerfile: Dockerfile.dev
    image: xsj-consulting-ui:latest
    container_name: xsj-consulting-ui
    environment:
      PORT: 4269
      HOST: 0.0.0.0
    ports:
      - 4269:4269
